apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: omega-{{ .Values.name }}-cron-workflow-template
  namespace: {{ .Values.namespace }}
spec:
  workflowSpec:
    arguments: {}
    workflowTemplateRef:
      name: omega-{{ .Values.name }}-workflow-template
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
