apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow-chart.fullname" . }}-secret
  labels:
    {{- include "workflow-chart.labels" . | nindent 4 }}
type: Opaque
data:
  omega_database_password: {{ .Values.omega.database.password | b64enc | quote }}
  rtds_database_password: {{ .Values.omega.rtds.password | b64enc | quote }}