apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: omega-{{ include "name" .}}-workflow-template
  namespace: {{ .Values.namespace }}
spec:
  entrypoint: main
  serviceAccountName: argo
  podGC:
    strategy: {{ .Values.podGC }}
  templates:
    - name: main
      container:
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy}}
        command: {{ .Values.container.command }}
        args: {{ .Values.container.args }}
        env:
          - name: TARGET_DIALECT
            value: "{{ .Values.omega.database.dialect }}"
          - name: TARGET_HOSTNAME
            value: "{{ .Values.omega.database.host }}"
          - name: TARGET_PORT
            value: "{{ .Values.omega.database.port }}"
          - name: TARGET_DATABASE
            value: "{{ .Values.omega.database.database }}"
          - name: TARGET_SCHEMA
            value: "{{ .Values.omega.database.schema }}"
          - name: TARGET_USER
            value: "{{ .Values.omega.database.username }}"
          - name: TARGET_PASSWORD_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "workflow-chart.fullname" . }}-secret
                key: omega_database_password
          - name: SOURCE_DIALECT
            value: "{{ .Values.omega.rtds.dialect }}"
          - name: SOURCE_HOSTNAME
            value: "{{ .Values.omega.rtds.host }}"
          - name: SOURCE_PORT
            value: "{{ .Values.omega.rtds.port }}"
          - name: SOURCE_DATABASE
            value: "{{ .Values.omega.rtds.database }}"
          - name: SOURCE_SCHEMA
            value: "{{ .Values.omega.rtds.schema }}"
          - name: SOURCE_USER
            value: "{{ .Values.omega.rtds.username }}"
          - name: SOURCE_DRIVER
            value: "{{ .Values.omega.rtds.driver }}"
          - name: SOURCE_PASSWORD_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "workflow-chart.fullname" . }}-secret
                key: rtds_database_password
          - name: API_GATEWAY_URL
            value: "{{ .Values.otc_hub.api_gateway_url }}"
          - name: FILE_STORE
            value: "{{ .Values.omega.data_processor.filestore }}"